### ISSUE TITLE
useContext vs localStorage

### ISSUE THREAD

**Issue by glrta** [fac25/tfb-cocoon-kids-big-hug#42]
Good use of localStorage to get things going and working 👏

I noticed you might want to use useContext to handle the useGroup in state which is a great call. Using some form of state management for things that the user can select and change is a popular solution so well worth the learning curve. 

I don’t know if you just didn’t have the time or are struggling, but I will recommend [this article either way](https://www.netlify.com/blog/2020/12/01/using-react-context-for-state-management-in-next.js/). I’d be happy to jump on a more hands on call if you need to get it to work. I did it locally too so could push what I have in a PR if that’s helpful. Anyways, I’m here if you need.

**Comment by mariapaz** [comment]
Hi Gio, thanks for the article. We refactored and moved the state to the context file, but then we got errors on pages when getting and setting the context. We'll have to move on now, but will keep this on mind next time we use global context.
